name: 2025-11-12

on: ['push']

jobs: 
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: what is your name
              run: echo 'My name is something you will never know'
    job2:
        runs-on: ubuntu-latest
        needs: job1
        steps:
            - name: How old are you
              run: echo 'You will never know my age'