name: example-workflow
on: [push]
jobs:
    hello-world:
        if: github.repository == 'DaliDalmas/playing-with-github-action'
        runs-on: ubuntu-latest
        steps:
            - name: "Hello world"
              run: echo "Hello world!"

    goodbye-moon:
        runs-on: ubuntu-latest
        steps:
            - name: "Repo name"
              run: echo "Repository name is ${GITHUB_REPOSITORY#*/}"
            - name: "Branch name"
              run: echo "Branch name is ${GITHUB_REF#refs/heads/}"